#
# .pre-commit-config.yaml - Shared Hooks
#
# Copyright (c) 2023 SNU Compbio Lab.
#
# SPDX-License-Identifier: MIT
#
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10240"] # 10MiB
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/seoklab/shared-hooks
    rev: v0.1.1
    hooks:
      - id: commitlint
default_install_hook_types:
  - pre-commit
  - pre-push
  - commit-msg
default_stages:
  - pre-commit
